// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "app": {
    "name": "Inky",
    "tagline": "Write first. Sync later."
  },
  "notes": {
    "empty": "No notes yet",
    "new": "New note"
  },
  "common": {
    "save": "Save",
    "cancel": "Cancel",
    "settings": "Settings"
  }
};
export default messages;